<a href="https://colab.research.google.com/github/KavyaD02/Continuous_Speech_Stress_Detection/blob/main/Stress_Level_Diagnosis_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os
import librosa
import librosa.display
from pydub.silence import split_on_silence
from pydub import AudioSegment, effects 
from scipy.io.wavfile import read, write

C:\Users\Kavya Duvvuri\anaconda3\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


In [ ]:
DATA_PATH = "./Data/"

def get_file_names(path = DATA_PATH):
    file_names = os.listdir(path)
    return file_names

def process_audio(audio_file_name):
    rate, audio = read(f"./Data/{audio_file_name}")

    aud = AudioSegment(audio.tobytes(), frame_rate = rate,
                         sample_width = audio.dtype.itemsize, channels = 1)

    audio_chunks = split_on_silence(
        aud,
        min_silence_len = 1000,
        silence_thresh = -50,
        keep_silence = 500,)
    
    # audio chunks are combined
    audio_processed = sum(audio_chunks)
    audio_processed = np.array(audio_processed.get_array_of_samples())
    audio_file = audio_file_name.split(".")[0]
    write(f"./Processed Data/{audio_file}_PROCESSED.wav", rate, audio_processed)

file_names = get_file_names()
for file_name in file_names:
    process_audio(file_name)
print("Done")

In [ ]:
def get_label_dict(df, file_list, test=False):
    label_dict = {}
    
    if test:
        df_list = df['PHQ_Score']
    else:
        df_list = df['PHQ8_Score']

    for file in file_list:
        patient_num = int(file.split("/")[-1].split("_")[0])

        patient_list = list(df['Participant_ID'])

        idx = patient_list.index(patient_num)

        phq8_score = int(df_list[idx])
        
        if phq8_score in range(0, 6):
            score = 0
        elif phq8_score in range(6, 15):
            score = 1
        elif phq8_score in range(15, 22):
            score = 2
        elif phq8_score in range(22, 28):
            score = 3

        label_dict[f"{file}"] = score
    
    return label_dict

In [ ]:
def get_set(df):
    df_files = [f"./Processed Data/{x}_AUDIO_PROCESSED.wav" for x in df['Participant_ID']]

    return list(set(df_files))

In [ ]:
train_df, test_df, val_df = pd.read_csv(f"./train.csv"), pd.read_csv(f"./test.csv"), pd.read_csv(f"./val.csv")

train, test, val = get_set(train_df), get_set(test_df), get_set(val_df)

In [ ]:
train_dict, test_dict, val_dict = get_label_dict(train_df, train), get_label_dict(test_df, test, True), get_label_dict(val_df, val)
data_dict = {**train_dict, **test_dict, **val_dict}

In [ ]:
PROCESSED_DATA_PATH = "./Processed Data/"

In [ ]:
data_list = list(data_dict.keys())
label_list = list(data_dict.values())

In [ ]:
new_data_list = []
new_label_list = []
for data in data_list:
    audios = os.listdir(PROCESSED_DATA_PATH)
    data_2 = data.split('/')[2]
    if data_2 in audios:
        new_data_list.append(data)
        new_label_list.append(label_list[data_list.index(data)])

## MFCC

In [ ]:
MFCC_Features_list = []
num_mfcc = 13
for i in new_data_list:
    audio, sr = librosa.load(i)
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=num_mfcc)
    delta = librosa.feature.delta(mfcc)
    delta_delta = librosa.feature.delta(delta)
    concatenated_features = np.concatenate((mfcc, delta, delta_delta), axis=0)
    mfcc_mean = np.mean(concatenated_features, axis=1)        
    
    MFCC_Features_list.append(mfcc_mean)

In [ ]:
MFCC_Features_list

[array([-4.7998880e+02,  8.1906418e+01,  2.3788067e+01,  2.7647785e+01,
         1.6417431e+01,  1.1871834e+01, -1.4654022e+00,  6.0309172e-01,
         3.4365511e+00, -2.2161488e-01,  1.6269801e+00, -2.9077635e-03,
         1.4428935e+00,  4.5108114e-04,  6.6430424e-04,  7.0557243e-04,
         6.9334876e-04,  6.0819526e-04,  4.9675320e-04,  4.1255978e-04,
         3.6070950e-04,  3.1199586e-04,  2.5605023e-04,  2.1645903e-04,
         2.1088055e-04,  2.1730018e-04, -8.5502412e-05, -9.6664400e-05,
        -4.2202457e-05,  6.0227781e-06,  2.7324335e-05,  2.8419801e-05,
         2.4964282e-05,  2.0813161e-05,  9.9289382e-06, -7.6197298e-06,
        -2.1439877e-05, -2.4345953e-05, -2.2957152e-05], dtype=float32),
 array([-4.8675009e+02,  8.7784813e+01,  1.3708212e+01,  1.7107145e+01,
         1.1889054e+01,  2.2367013e+00, -4.6829233e+00,  3.4260835e-02,
         1.0244027e+00, -2.6195076e+00, -2.1286905e+00, -4.9599227e-01,
        -4.8767224e-02,  5.0314730e-03,  2.9077360e-03, -2.1617

In [ ]:
import pandas as pd

MFCC_df = pd.DataFrame({"MFCC": MFCC_Features_list})

MFCC_df.to_csv("MFCC Features.csv")

## Chroma

In [ ]:
Chroma_Features_list = []
for i in new_data_list:
    audio, sr = librosa.load(i)
    chroma_features = librosa.feature.chroma_stft(y=audio, sr=sr)
    chroma_features_mean = np.mean(chroma_features, axis=1)            
    
    Chroma_Features_list.append(chroma_features_mean)

In [ ]:
Chroma_Features_list

[array([0.39278206, 0.40645158, 0.40921256, 0.43215534, 0.4711194 ,
        0.5265093 , 0.5633142 , 0.55364215, 0.47984564, 0.43670607,
        0.4095279 , 0.39502215], dtype=float32),
 array([0.4751777 , 0.45168445, 0.4198884 , 0.41026643, 0.4258831 ,
        0.4379993 , 0.42734665, 0.39209974, 0.38465264, 0.43427554,
        0.5016243 , 0.5121742 ], dtype=float32),
 array([0.4800195 , 0.49913052, 0.5191515 , 0.53731936, 0.53146565,
        0.50959057, 0.47921512, 0.46848714, 0.46503764, 0.47736695,
        0.47865093, 0.47064006], dtype=float32),
 array([0.44089606, 0.46302846, 0.49351683, 0.5125475 , 0.51613414,
        0.50857073, 0.48448017, 0.46599898, 0.45242655, 0.46066296,
        0.45471823, 0.43799806], dtype=float32),
 array([0.47000822, 0.45017734, 0.43637407, 0.43163916, 0.4452612 ,
        0.4336406 , 0.43312964, 0.45615423, 0.53752357, 0.5588399 ,
        0.5635253 , 0.5252082 ], dtype=float32),
 array([0.39373022, 0.38772783, 0.3897804 , 0.40496138, 0.42657682,
       

In [ ]:
len(Chroma_Features_list)

186

In [ ]:
import pandas as pd

Chroma_df = pd.DataFrame({"Chroma": Chroma_Features_list})

Chroma_df.to_csv("Chroma Features.csv")

## LogFBank Features

In [ ]:
import scipy.io.wavfile as wav
from python_speech_features import mfcc, logfbank

fbank_features = []
for i in new_data_list:
# Load the speech file
    (rate, signal) = wav.read(i)

# Extract log filter bank energies
    fbank_feat = logfbank(signal, rate, nfilt=13)

    fbank_features_mean = np.mean(fbank_feat, axis=0) 
    fbank_features.append(fbank_features_mean)
    
fbank_features

[array([7.59823394, 7.77365867, 7.79413678, 6.99811312, 6.79225233,
        7.18417241, 7.70277448, 7.81721754, 7.58491191, 7.61343345,
        7.86079871, 8.10093761, 7.11125604]),
 array([7.0747439 , 7.89069925, 8.00342055, 7.50475736, 7.2238409 ,
        7.40201359, 7.79588895, 8.14516021, 7.76742839, 7.53181991,
        7.36971333, 7.27398831, 6.95928654]),
 array([ 9.00598761,  9.71864762, 10.15820319,  9.80285939,  9.58536398,
         9.89616642, 10.16399075, 10.46539744, 10.20691903,  9.90252893,
         8.88730482,  8.18423942,  7.90915049]),
 array([7.46310843, 7.87013798, 8.11563016, 7.82648359, 7.5610815 ,
        7.64503209, 7.91960168, 7.91637355, 8.30093625, 8.42328993,
        8.5475073 , 7.82887091, 7.0682157 ]),
 array([7.53840766, 7.41262902, 7.84480819, 7.61965327, 7.31402502,
        7.25859623, 7.24793998, 7.31433076, 7.3369797 , 6.99663123,
        8.06243592, 8.37533372, 7.65497152]),
 array([ 8.61804103,  9.2913785 ,  9.81368635,  9.36881567,  9.11733349,
    

In [ ]:
print(len(fbank_features))

186


In [ ]:
import pandas as pd

logfbank_df = pd.DataFrame({"LogFbank": fbank_features})

logfbank_df.to_csv("LogFbank Features.csv")

In [ ]:
len(new_data_list)

186

## LPC Features

In [ ]:
import numpy as np
import librosa

lpc_features = []
for j in new_data_list:

    audio, sr = librosa.load(j)

    # Pre-emphasis
    pre_emphasis = 0.97
    emphasized_audio = np.append(audio[0], audio[1:] - pre_emphasis * audio[:-1])

    # Framing the audio signal
    frame_size = 0.025  # 25 milliseconds
    frame_stride = 0.01  # 10 milliseconds
    frame_length = int(round(frame_size * sr))
    frame_step = int(round(frame_stride * sr))
    num_frames = int(np.ceil(float(np.abs(len(emphasized_audio) - frame_length)) / frame_step))

    # Padding the audio signal to make sure all frames have equal length
    pad_audio_length = num_frames * frame_step + frame_length
    padded_audio = np.pad(emphasized_audio, (0, pad_audio_length - len(emphasized_audio)), 'constant')

    # Splitting the audio signal into frames
    indices = np.tile(np.arange(0, frame_length), (num_frames, 1)) + np.tile(
        np.arange(0, num_frames * frame_step, frame_step), (frame_length, 1)).T
    frames = padded_audio[indices.astype(np.int32, copy=False)]
    
    # Applying the LPC analysis
    order = 12  # Number of LPC coefficients (higher values give more precise modeling but require more computational resources)
    lpc_coeffs = np.zeros((num_frames, order + 1))
    for k in range(num_frames):
        temp = frames[k, :]
        all_zeros = not np.any(temp)
        if all_zeros:
            continue
        else:
            lpc_coeffs[k, :] = librosa.lpc(temp, order)
    
    lpc_coeffs_mean = np.mean(lpc_coeffs, axis=0)  
    lpc_features.append(lpc_coeffs_mean)
print(lpc_features)
print(len(lpc_features))

[array([  1.        ,  -3.20140654,   6.68002795, -10.92327038,
        14.99900233, -17.67281193,  18.12448776, -16.25538979,
        12.64547968,  -8.40180957,   4.62109887,  -1.9602508 ,
         0.49918895]), array([  0.99964466,  -3.64968756,   8.56736564, -14.99073709,
        21.40927018, -25.79066593,  26.75498499, -23.95580951,
        18.40311885, -11.87262242,   6.18744048,  -2.38951554,
         0.55936636]), array([  1.        ,  -3.3260363 ,   7.07356518, -11.66591546,
        16.13055952, -19.06334853,  19.57966293, -17.54620146,
        13.61799765,  -8.99820634,   4.90833055,  -2.02010328,
         0.49514442]), array([  1.        ,  -3.6546965 ,   8.09281494, -13.48395669,
        18.59844435, -22.01272369,  22.59950547, -20.13417011,
        15.48678574, -10.10971482,   5.35863116,  -2.10221707,
         0.47807803]), array([  1.        ,  -3.09807429,   6.66580053, -11.08517416,
        15.39340014, -18.17036112,  18.64565901, -16.59778191,
        12.7687592 ,  -8.

In [ ]:
import pandas as pd

LPC_df = pd.DataFrame({"LPC": lpc_features})

LPC_df.to_csv("LPC Features.csv")

In [ ]:
import librosa
import numpy as np

plpc_features = []
for j in new_data_list[1:]:
    speech_signal, sample_rate = librosa.load(j)
    print(j)
    print(speech_signal)
    frame_length = int(0.02 * sample_rate)
    hop_length = int(0.01 * sample_rate)
    speech_frames = librosa.util.frame(speech_signal, frame_length=frame_length, hop_length=hop_length).T

    windowed_frames = speech_frames * np.hamming(frame_length)

    model_order = 12
    lpc_coefficients = np.zeros((len(windowed_frames), model_order + 1))
    for i, frame in enumerate(windowed_frames):
        lpc_coefficients[i] = librosa.lpc(frame, order=model_order)

    lsf_coefficients = np.zeros_like(lpc_coefficients)
    for i, lpc_coeffs in enumerate(lpc_coefficients):
        lpc_coeffs = np.append(lpc_coeffs, 0)  
        roots = np.roots(lpc_coeffs)  
        angles = np.angle(roots)
        sorted_indices = np.argsort(angles)
        lsf_coefficients[i] = np.sort(angles[sorted_indices])

    perceptual_coefficients = np.mean(np.array(lsf_coefficients), axis = 0)
    plpc_features.append(perceptual_coefficients)
print(len(perceptual_coefficients))

./Processed Data/336_AUDIO_PROCESSED.wav
[ 3.5482313e-04  3.9170982e-04  2.6061884e-04 ... -2.5118365e-07
  5.0521783e-07  0.0000000e+00]
./Processed Data/369_AUDIO_PROCESSED.wav
[-0.00017955 -0.00022731 -0.00020593 ...  0.00914233  0.00942815
  0.        ]
./Processed Data/321_AUDIO_PROCESSED.wav
[-0.00036047 -0.00044896 -0.00040709 ... -0.05007971 -0.05330844
  0.        ]
./Processed Data/485_AUDIO_PROCESSED.wav
[-4.1331243e-04 -5.2932877e-04 -4.3086644e-04 ... -2.8430641e-05
  1.1685224e-05  0.0000000e+00]
./Processed Data/479_AUDIO_PROCESSED.wav
[-0.00056059 -0.00054805 -0.00041175 ... -0.00102879 -0.00098227
  0.        ]
./Processed Data/318_AUDIO_PROCESSED.wav
[ 5.6964756e-05  3.6751710e-05  5.3029762e-05 ...  7.8367448e-04
 -8.2812796e-04  0.0000000e+00]
./Processed Data/353_AUDIO_PROCESSED.wav
[-0.00036398 -0.00045966 -0.00037411 ... -0.00482294 -0.00452319
  0.        ]
./Processed Data/338_AUDIO_PROCESSED.wav
[0.0003828  0.00040107 0.00039171 ... 0.00192297 0.00224205 0.   

FloatingPointError: numerical error, input ill-conditioned?

## Combined Features

In [ ]:
csv_path = "./MFCC Features.csv"
MFCC_df = pd.read_csv(csv_path)
MFCC_Features = list(MFCC_df["MFCC"])
MFCC_Features_list = []
for i in MFCC_Features:
    new_i = i.replace('\n', ' ')
    new_i = new_i.replace('[', '')
    new_i = new_i.replace(']', '')
    array_data = np.fromstring(new_i, dtype=np.float64, sep=' ')
    MFCC_Features_list.append(array_data)
print(MFCC_Features_list)

[array([-4.7998880e+02,  8.1906418e+01,  2.3788067e+01,  2.7647785e+01,
        1.6417431e+01,  1.1871834e+01, -1.4654022e+00,  6.0309172e-01,
        3.4365511e+00, -2.2161488e-01,  1.6269801e+00, -2.9077635e-03,
        1.4428935e+00,  4.5108114e-04,  6.6430424e-04,  7.0557243e-04,
        6.9334876e-04,  6.0819526e-04,  4.9675320e-04,  4.1255978e-04,
        3.6070950e-04,  3.1199586e-04,  2.5605023e-04,  2.1645903e-04,
        2.1088055e-04,  2.1730018e-04, -8.5502412e-05, -9.6664400e-05,
       -4.2202457e-05,  6.0227781e-06,  2.7324335e-05,  2.8419801e-05,
        2.4964282e-05,  2.0813161e-05,  9.9289382e-06, -7.6197298e-06,
       -2.1439877e-05, -2.4345953e-05, -2.2957152e-05]), array([-4.8675009e+02,  8.7784813e+01,  1.3708212e+01,  1.7107145e+01,
        1.1889054e+01,  2.2367013e+00, -4.6829233e+00,  3.4260835e-02,
        1.0244027e+00, -2.6195076e+00, -2.1286905e+00, -4.9599227e-01,
       -4.8767224e-02,  5.0314730e-03,  2.9077360e-03, -2.1617715e-03,
       -1.4750299e-

In [ ]:
csv_path = "./Chroma Features.csv"
Chroma_df = pd.read_csv(csv_path)
Chroma_Features = list(Chroma_df["Chroma"])
Chroma_Features_list = []
for i in Chroma_Features:
    new_i = i.replace('\n', ' ')
    new_i = new_i.replace('[', '')
    new_i = new_i.replace(']', '')
    array_data = np.fromstring(new_i, dtype=np.float64, sep=' ')
    Chroma_Features_list.append(array_data)
print(Chroma_Features_list)

[array([0.39278206, 0.40645158, 0.40921256, 0.43215534, 0.4711194 ,
       0.5265093 , 0.5633142 , 0.55364215, 0.47984564, 0.43670607,
       0.4095279 , 0.39502215]), array([0.4751777 , 0.45168445, 0.4198884 , 0.41026643, 0.4258831 ,
       0.4379993 , 0.42734665, 0.39209974, 0.38465264, 0.43427554,
       0.5016243 , 0.5121742 ]), array([0.4800195 , 0.49913052, 0.5191515 , 0.53731936, 0.53146565,
       0.50959057, 0.47921512, 0.46848714, 0.46503764, 0.47736695,
       0.47865093, 0.47064006]), array([0.44089606, 0.46302846, 0.49351683, 0.5125475 , 0.51613414,
       0.50857073, 0.48448017, 0.46599898, 0.45242655, 0.46066296,
       0.45471823, 0.43799806]), array([0.47000822, 0.45017734, 0.43637407, 0.43163916, 0.4452612 ,
       0.4336406 , 0.43312964, 0.45615423, 0.53752357, 0.5588399 ,
       0.5635253 , 0.5252082 ]), array([0.39373022, 0.38772783, 0.3897804 , 0.40496138, 0.42657682,
       0.4459193 , 0.46725714, 0.49015749, 0.48909155, 0.4745155 ,
       0.44127667, 0.41186914]

In [ ]:
csv_path = "./LogFbank Features.csv"
fbank_df = pd.read_csv(csv_path)
fbank_Features = list(fbank_df["LogFbank"])
fbank_features = []
for i in fbank_Features:
    new_i = i.replace('\n', ' ')
    new_i = new_i.replace('[', '')
    new_i = new_i.replace(']', '')
    array_data = np.fromstring(new_i, dtype=np.float64, sep=' ')
    fbank_features.append(array_data)
print(fbank_features)

[array([7.59823394, 7.77365867, 7.79413678, 6.99811312, 6.79225233,
       7.18417241, 7.70277448, 7.81721754, 7.58491191, 7.61343345,
       7.86079871, 8.10093761, 7.11125604]), array([7.0747439 , 7.89069925, 8.00342055, 7.50475736, 7.2238409 ,
       7.40201359, 7.79588895, 8.14516021, 7.76742839, 7.53181991,
       7.36971333, 7.27398831, 6.95928654]), array([ 9.00598761,  9.71864762, 10.15820319,  9.80285939,  9.58536398,
        9.89616642, 10.16399075, 10.46539744, 10.20691903,  9.90252893,
        8.88730482,  8.18423942,  7.90915049]), array([7.46310843, 7.87013798, 8.11563016, 7.82648359, 7.5610815 ,
       7.64503209, 7.91960168, 7.91637355, 8.30093625, 8.42328993,
       8.5475073 , 7.82887091, 7.0682157 ]), array([7.53840766, 7.41262902, 7.84480819, 7.61965327, 7.31402502,
       7.25859623, 7.24793998, 7.31433076, 7.3369797 , 6.99663123,
       8.06243592, 8.37533372, 7.65497152]), array([ 8.61804103,  9.2913785 ,  9.81368635,  9.36881567,  9.11733349,
        9.54436979,

In [ ]:
csv_path = "./LPC Features.csv"
lpc_df = pd.read_csv(csv_path)
lpc_Features = list(lpc_df["LPC"])
lpc_features = []
for i in lpc_Features:
    new_i = i.replace('\n', ' ')
    new_i = new_i.replace('[', '')
    new_i = new_i.replace(']', '')
    array_data = np.fromstring(new_i, dtype=np.float64, sep=' ')
    lpc_features.append(array_data)
print(lpc_features)

[array([  1.        ,  -3.20140654,   6.68002795, -10.92327038,
        14.99900233, -17.67281193,  18.12448776, -16.25538979,
        12.64547968,  -8.40180957,   4.62109887,  -1.9602508 ,
         0.49918895]), array([  0.99964466,  -3.64968756,   8.56736564, -14.99073709,
        21.40927018, -25.79066593,  26.75498499, -23.95580951,
        18.40311885, -11.87262242,   6.18744048,  -2.38951554,
         0.55936636]), array([  1.        ,  -3.3260363 ,   7.07356518, -11.66591546,
        16.13055952, -19.06334853,  19.57966293, -17.54620146,
        13.61799765,  -8.99820634,   4.90833055,  -2.02010328,
         0.49514442]), array([  1.        ,  -3.6546965 ,   8.09281494, -13.48395669,
        18.59844435, -22.01272369,  22.59950547, -20.13417011,
        15.48678574, -10.10971482,   5.35863116,  -2.10221707,
         0.47807803]), array([  1.        ,  -3.09807429,   6.66580053, -11.08517416,
        15.39340014, -18.17036112,  18.64565901, -16.59778191,
        12.7687592 ,  -8.

In [ ]:
combined_features = []
for feature_id in range(186):
    combined_feature = np.append(MFCC_Features_list[feature_id], Chroma_Features_list[feature_id])
    combined_feature = np.append(combined_feature, lpc_features[feature_id])
    combined_feature = np.append(combined_feature, fbank_features[feature_id])
    combined_features.append(combined_feature)

In [ ]:
combined_features

[array([-4.79988800e+02,  8.19064180e+01,  2.37880670e+01,  2.76477850e+01,
         1.64174310e+01,  1.18718340e+01, -1.46540220e+00,  6.03091720e-01,
         3.43655110e+00, -2.21614880e-01,  1.62698010e+00, -2.90776350e-03,
         1.44289350e+00,  4.51081140e-04,  6.64304240e-04,  7.05572430e-04,
         6.93348760e-04,  6.08195260e-04,  4.96753200e-04,  4.12559780e-04,
         3.60709500e-04,  3.11995860e-04,  2.56050230e-04,  2.16459030e-04,
         2.10880550e-04,  2.17300180e-04, -8.55024120e-05, -9.66644000e-05,
        -4.22024570e-05,  6.02277810e-06,  2.73243350e-05,  2.84198010e-05,
         2.49642820e-05,  2.08131610e-05,  9.92893820e-06, -7.61972980e-06,
        -2.14398770e-05, -2.43459530e-05, -2.29571520e-05,  3.92782060e-01,
         4.06451580e-01,  4.09212560e-01,  4.32155340e-01,  4.71119400e-01,
         5.26509300e-01,  5.63314200e-01,  5.53642150e-01,  4.79845640e-01,
         4.36706070e-01,  4.09527900e-01,  3.95022150e-01,  1.00000000e+00,
        -3.2

In [ ]:
import pandas as pd

combined_df = pd.DataFrame({"Combined": combined_features})

combined_df.to_csv("Combined Features.csv")

In [ ]:
import librosa

audio_path = "./Processed Data/300_AUDIO_PROCESSED.wav"
signal, sr = librosa.load(audio_path, sr=None)
pre_emphasized_signal = librosa.effects.preemphasis(signal) 

frame_length = 1024
hop_length = 256
frames = librosa.util.frame(pre_emphasized_signal, frame_length=frame_length, hop_length=hop_length).T
frames *= librosa.filters.get_window('hann', frame_length, fftbins=True) 
stft = librosa.stft(frames.flatten(), center=False)

mel_basis = librosa.filters.mel(sr, n_fft=frame_length) 
print(mel_basis.shape)
print(stft.shape)
mel_spectrum = mel_basis.T.dot(stft)
lpc_order = 12
plpc_coeffs = librosa.lpc(librosa.amplitude_to_db(mel_spectrum), lpc_order)

print("PLPC Coefficients:") 
print(plpc_coeffs)

(128, 513)
(1025, 37991)


ValueError: shapes (513,128) and (1025,37991) not aligned: 128 (dim 1) != 1025 (dim 0)

In [ ]:
import numpy as np
import scipy.signal as signal
import librosa

audio_path = "./Processed Data/300_AUDIO_PROCESSED.wav"
audio_signal, sr = librosa.load(audio_path, sr=None)

num_channels = 40
frequencies = librosa.filters.gammatone_frequencies(sr, num_channels)

# Compute the Gammatone filterbank
filterbank = signal.gammatone(audio_signal, frequencies)

power_spectrum = np.abs(filterbank) ** 2
log_compressed = np.log(power_spectrum)
gfcc = librosa.feature.mfcc(S=log_compressed, n_mfcc=num_channels)
num_coefficients = 12
gfcc_coefficients = gfcc[:num_coefficients]

print("GFCC Coefficients:")
print(gfcc_coefficients)

AttributeError: module 'librosa.filters' has no attribute 'gammatone_frequencies'

In [ ]:
import librosa

audio_path = "output_part_1.wav"
signal, sr = librosa.load(audio_path, sr=None)
pre_emphasized_signal = librosa.effects.preemphasis(signal)
pre_emphasized_signal = librosa.to_mono(pre_emphasized_signal)

frame_length = 1024
hop_length = 256
frames = librosa.util.frame(pre_emphasized_signal, frame_length=frame_length, hop_length=hop_length).T
frames *= librosa.filters.get_window('hann', frame_length, fftbins=True)
stft = librosa.stft(frames.flatten(), center=False)

mel_basis = librosa.filters.mel(sr, n_fft=frame_length)
mel_spectrum = mel_basis.dot(stft)
lpc_order = 12
plpc_coeffs = librosa.lpc(librosa.amplitude_to_db(mel_spectrum), lpc_order)

print("PLPC Coefficients:")
print(plpc_coeffs)

ValueError: shapes (128,513) and (1025,10325) not aligned: 513 (dim 1) != 1025 (dim 0)

In [ ]:
from github import Github
import os

# GitHub repository information
repo_owner = "KavyaD02"
repo_name = "Continuous_Speech_Stress_Detection"
repo_path = f"{repo_owner}/{repo_name}/Data"

# Local directory path
local_dir = "./Data/"

# GitHub credentials
access_token = "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"

# Create a GitHub instance
g = Github(access_token)

# Get the repository
repo = g.get_repo(repo_path)

# Iterate over the files in the local directory
for root, dirs, files in os.walk(local_dir):
    for file in files:
        # Local file path
        local_file_path = os.path.join(root, file)

        # Remote file path
        remote_file_path = os.path.join(root.replace(local_dir, ""), file).lstrip("/")

        # Read the content of the local file
        with open(local_file_path, "rb") as f:
            file_content = f.read()

        # Create or update the file in the repository
        repo.create_file(remote_file_path, f"Upload {remote_file_path}", file_content)

ImportError: cannot import name 'Github' from 'github' (C:\Users\Kavya Duvvuri\anaconda3\lib\site-packages\github\__init__.py)

In [ ]:
!pip show PyGitHub

Name: PyGithub
Version: 1.58.2
Summary: Use the full Github API v3
Home-page: https://github.com/pygithub/pygithub
Author: Vincent Jacques
Author-email: vincent@vincent-jacques.net
License: 
Location: c:\users\kavya duvvuri\anaconda3\lib\site-packages
Requires: deprecated, pyjwt, pynacl, requests
Required-by: 


In [ ]:
!pip install github


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!pip install --upgrade PyGitHub


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
